# Generated by Django 5.2.5 on 2025-12-07 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_alter_projectmembership_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_special", models.BooleanField(default=False)),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام کامل"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("answered", "پاسخ داد"),
                            ("no_answer", "پاسخ نداد"),
                            ("pending", "در حال انتظار"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت تماس",
                    ),
                ),
                (
                    "last_call_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تماس"
                    ),
                ),
                (
                    "custom_fields",
                    models.TextField(
                        blank=True, null=True, verbose_name="فیلدهای سفارشی"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "مرد"),
                            ("female", "زن"),
                            ("none", "ترجیح میدهم که نگویم"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_caller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تماس\u200cگیرنده تخصیص داده شده",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد شده توسط",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مخاطب",
                "verbose_name_plural": "مخاطبین",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="اقدام")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="contacts.contact",
                        verbose_name="مخاطب",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ مخاطب",
                "verbose_name_plural": "لاگ\u200cهای مخاطب",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["project", "assigned_caller", "call_status", "is_active"],
                name="contacts_co_project_05d89e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["gender"], name="contacts_co_gender_c39385_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("project", "phone")},
        ),
        migrations.AddIndex(
            model_name="contactlog",
            index=models.Index(
                fields=["timestamp"], name="contacts_co_timesta_b23891_idx"
            ),
        ),
    ]
