# Generated by Django 5.2.5 on 2025-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_special", models.BooleanField(default=False)),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام کامل"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("wrong_number", "شماره اشتباه"),
                            ("answered", "پاسخ داد"),
                            ("no_answer", "پاسخ نداد"),
                            ("pending", "در حال انتظار"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت تماس",
                    ),
                ),
                (
                    "last_call_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تماس"
                    ),
                ),
                (
                    "custom_fields",
                    models.TextField(
                        blank=True, null=True, verbose_name="فیلدهای سفارشی"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "مرد"),
                            ("female", "زن"),
                            ("none", "ترجیح میدهم که نگویم"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "مخاطب",
                "verbose_name_plural": "مخاطبین",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="اقدام")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
            ],
            options={
                "verbose_name": "لاگ مخاطب",
                "verbose_name_plural": "لاگ\u200cهای مخاطب",
                "ordering": ["-timestamp"],
            },
        ),
    ]
