# Generated by Django 5.2.5 on 2025-11-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assigned_caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='تماس\u200cگیرنده تخصیص داده شده'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_contacts', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='projects.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contact', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مخاطب'),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='contacts.contact', verbose_name='مخاطب'),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام شده توسط'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('project', 'phone')},
        ),
    ]
