# Generated by Django 5.2.5 on 2025-11-21 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactlog",
            index=models.Index(
                fields=["timestamp"], name="contacts_co_timesta_b23891_idx"
            ),
        ),
    ]
