# Generated by Django 5.2.5 on 2025-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_contactlog_contacts_co_timesta_b23891_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="call_status",
            field=models.CharField(
                choices=[
                    ("answered", "پاسخ داد"),
                    ("no_answer", "پاسخ نداد"),
                    ("pending", "در حال انتظار"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت تماس",
            ),
        ),
    ]
