# Generated by Django 5.2.5 on 2025-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="نام پروژه")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("inactive", "غیرفعال"),
                            ("completed", "تکمیل شده"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "پروژه",
                "verbose_name_plural": "پروژه\u200cها",
                "ordering": ["-created_at"],
                "permissions": [("manage_project", "Can manage project")],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "ادمین"),
                            ("caller", "تماس\u200cگیرنده"),
                            ("contact", "مخاطب"),
                        ],
                        max_length=20,
                        verbose_name="نقش در پروژه",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ تخصیص"),
                ),
            ],
            options={
                "verbose_name": "عضویت در پروژه",
                "verbose_name_plural": "عضویت\u200cها در پروژه\u200cها",
                "ordering": ["-assigned_at"],
            },
        ),
    ]
