# Generated by Django 5.2.5 on 2025-12-05 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_question_answerchoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmembership",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_callers",
                to="projects.project",
                verbose_name="پروژه",
            ),
        ),
    ]
