# Generated by Django 5.2.5 on 2025-12-07 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ تماس",
                "verbose_name_plural": "پاسخ تماس ها",
            },
        ),
        migrations.CreateModel(
            name="CallEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edit_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ تغییر"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="نام فیلد"),
                ),
                ("old_value", models.TextField(blank=True, verbose_name="ارزش گذشته")),
                ("new_value", models.TextField(blank=True, verbose_name="ارزش جدید")),
                (
                    "edit_reason",
                    models.TextField(blank=True, verbose_name="دلیل تغییر"),
                ),
            ],
            options={
                "verbose_name": "تاریخجه ادیت تماس",
                "verbose_name_plural": "تاریخجه ادیت تماس ها",
                "ordering": ["-edit_date"],
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_date",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="تاریخ تماس"
                    ),
                ),
                (
                    "call_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("interested", "Interested"),
                            ("no_time", "No time"),
                            ("not_interested", "Not interested"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="جزییات تماس",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wrong_number", "Wrong number"),
                            ("answered", "Answered"),
                            ("no_answer", "No answer"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                ("feedback", models.TextField(blank=True, verbose_name="بازخورد")),
                (
                    "detailed_report",
                    models.TextField(blank=True, verbose_name="جزییات گزارش"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت تماس(به ثانیه)"
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, verbose_name="نیاز به پیگیری دارد"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پیگیری"
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="قابل تغییر"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تغییر داده شده در"
                    ),
                ),
                (
                    "edit_reason",
                    models.TextField(blank=True, verbose_name="دلیل تغییر"),
                ),
                (
                    "original_data",
                    models.JSONField(blank=True, verbose_name="داده اورجینال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="ایجاد شده در"
                    ),
                ),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تماس گیرنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تماسس",
                "verbose_name_plural": "تماس ها",
                "ordering": ["-call_date"],
            },
        ),
    ]
