# Generated by Django 5.2.5 on 2025-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تماس')),
                ('call_result', models.CharField(blank=True, choices=[('interested', 'علاقه\u200cمند هست'), ('no_time', 'وقت ندارد'), ('not_interested', 'علاقه\u200cمند نیست')], max_length=50, null=True, verbose_name='نتیجه تماس')),
                ('status', models.CharField(choices=[('wrong_number', 'شماره اشتباه'), ('answered', 'پاسخ داد'), ('no_answer', 'پاسخ نداد'), ('pending', 'در انتظار')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('feedback', models.TextField(blank=True, verbose_name='بازخورد')),
                ('detailed_report', models.TextField(blank=True, verbose_name='گزارش تفصیلی')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت تماس (ثانیه)')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='نیاز به پیگیری')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پیگیری')),
                ('is_editable', models.BooleanField(default=True, verbose_name='قابل ویرایش')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش')),
                ('edit_reason', models.TextField(blank=True, verbose_name='دلیل ویرایش')),
                ('original_data', models.TextField(blank=True, verbose_name='داده\u200cهای اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='CallAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'پاسخ تماس',
                'verbose_name_plural': 'پاسخ\u200cهای تماس',
            },
        ),
        migrations.CreateModel(
            name='CallEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')),
                ('field_name', models.CharField(max_length=50, verbose_name='نام فیلد')),
                ('old_value', models.TextField(blank=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, verbose_name='مقدار جدید')),
                ('edit_reason', models.TextField(blank=True, verbose_name='دلیل ویرایش')),
            ],
            options={
                'verbose_name': 'تاریخچه ویرایش تماس',
                'verbose_name_plural': 'تاریخچه ویرایش تماس\u200cها',
                'ordering': ['-edit_date'],
            },
        ),
    ]
