# Generated by Django 5.2.5 on 2025-11-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('contacts', '0001_initial'),
        ('files', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='تماس\u200cگیرنده'),
        ),
        migrations.AddField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='contacts.contact', verbose_name='مخاطب'),
        ),
        migrations.AddField(
            model_name='call',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_calls', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش شده توسط'),
        ),
        migrations.AddField(
            model_name='call',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='projects.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='callanswer',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='calls.call', verbose_name='تماس'),
        ),
        migrations.AddField(
            model_name='callanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.question', verbose_name='سوال'),
        ),
        migrations.AddField(
            model_name='callanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.answerchoice', verbose_name='گزینه انتخاب\u200cشده'),
        ),
        migrations.AddField(
            model_name='calledithistory',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='calls.call', verbose_name='تماس'),
        ),
        migrations.AddField(
            model_name='calledithistory',
            name='edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_edits', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش شده توسط'),
        ),
        migrations.AlterUniqueTogether(
            name='callanswer',
            unique_together={('call', 'question')},
        ),
    ]
