# Generated by Django 5.2.5 on 2025-12-07 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calls", "0001_initial"),
        ("contacts", "0001_initial"),
        ("projects", "0004_alter_projectmembership_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="contacts.contact",
                verbose_name="مخاطب",
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تغییر کرده توسط",
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="projects.project",
                verbose_name="پروژه",
            ),
        ),
        migrations.AddField(
            model_name="callanswer",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="calls.call",
                verbose_name="تماس",
            ),
        ),
        migrations.AddField(
            model_name="callanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.question",
                verbose_name="سوال",
            ),
        ),
        migrations.AddField(
            model_name="callanswer",
            name="selected_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.answerchoice",
                verbose_name="گزینه انتخاب شده",
            ),
        ),
        migrations.AddField(
            model_name="calledithistory",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edit_history",
                to="calls.call",
                verbose_name="تماس",
            ),
        ),
        migrations.AddField(
            model_name="calledithistory",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_edits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تفییر داده شده توسط",
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["call_date"], name="calls_call_call_da_9b05bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["contact"], name="calls_call_contact_153ebe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["project"], name="calls_call_project_1e0463_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="callanswer",
            unique_together={("call", "question")},
        ),
        migrations.AddIndex(
            model_name="calledithistory",
            index=models.Index(
                fields=["edit_date"], name="calls_calle_edit_da_2409e6_idx"
            ),
        ),
    ]
