# Generated by Django 5.2.5 on 2025-12-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CallEditHistory",
        ),
    ]
