# Generated by Django 5.2.5 on 2025-11-24 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_initial"),
        ("contacts", "0003_contactlog_contacts_co_timesta_b23891_idx"),
        ("projects", "0003_question_answerchoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="call",
            options={
                "ordering": ["-call_date"],
                "verbose_name": "Call",
                "verbose_name_plural": "Calls",
            },
        ),
        migrations.AlterModelOptions(
            name="callanswer",
            options={
                "verbose_name": "Call Answer",
                "verbose_name_plural": "Call Answers",
            },
        ),
        migrations.AlterModelOptions(
            name="calledithistory",
            options={
                "ordering": ["-edit_date"],
                "verbose_name": "Call Edit History",
                "verbose_name_plural": "Call Edit Histories",
            },
        ),
        migrations.AlterField(
            model_name="call",
            name="call_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Call Date"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="call_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interested", "Interested"),
                    ("no_time", "No time"),
                    ("not_interested", "Not interested"),
                ],
                max_length=50,
                null=True,
                verbose_name="Call Result",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="caller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Caller",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="contacts.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="call",
            name="detailed_report",
            field=models.TextField(blank=True, verbose_name="Detailed Report"),
        ),
        migrations.AlterField(
            model_name="call",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Call Duration (seconds)"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="edit_reason",
            field=models.TextField(blank=True, verbose_name="Edit Reason"),
        ),
        migrations.AlterField(
            model_name="call",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Edited At"),
        ),
        migrations.AlterField(
            model_name="call",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Edited By",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="feedback",
            field=models.TextField(blank=True, verbose_name="Feedback"),
        ),
        migrations.AlterField(
            model_name="call",
            name="follow_up_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Follow-up Date"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="follow_up_required",
            field=models.BooleanField(default=False, verbose_name="Requires Follow-up"),
        ),
        migrations.AlterField(
            model_name="call",
            name="is_editable",
            field=models.BooleanField(default=True, verbose_name="Editable"),
        ),
        migrations.AlterField(
            model_name="call",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="call",
            name="original_data",
            field=models.JSONField(blank=True, verbose_name="Original Data"),
        ),
        migrations.AlterField(
            model_name="call",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="projects.project",
                verbose_name="Project",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="status",
            field=models.CharField(
                choices=[
                    ("wrong_number", "Wrong number"),
                    ("answered", "Answered"),
                    ("no_answer", "No answer"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="callanswer",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="calls.call",
                verbose_name="Call",
            ),
        ),
        migrations.AlterField(
            model_name="callanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.question",
                verbose_name="Question",
            ),
        ),
        migrations.AlterField(
            model_name="callanswer",
            name="selected_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.answerchoice",
                verbose_name="Selected Choice",
            ),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edit_history",
                to="calls.call",
                verbose_name="Call",
            ),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="edit_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Edit Date"
            ),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="edit_reason",
            field=models.TextField(blank=True, verbose_name="Edit Reason"),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_edits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Edited By",
            ),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="field_name",
            field=models.CharField(max_length=50, verbose_name="Field Name"),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="new_value",
            field=models.TextField(blank=True, verbose_name="New Value"),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="old_value",
            field=models.TextField(blank=True, verbose_name="Old Value"),
        ),
    ]
