# Generated by Django 5.2.5 on 2025-11-24 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_alter_call_options_alter_callanswer_options_and_more"),
        ("contacts", "0003_contactlog_contacts_co_timesta_b23891_idx"),
        ("projects", "0003_question_answerchoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="call",
            options={
                "ordering": ["-call_date"],
                "verbose_name": "تماسس",
                "verbose_name_plural": "تماس ها",
            },
        ),
        migrations.AlterModelOptions(
            name="callanswer",
            options={
                "verbose_name": "پاسخ تماس",
                "verbose_name_plural": "پاسخ تماس ها",
            },
        ),
        migrations.AlterModelOptions(
            name="calledithistory",
            options={
                "ordering": ["-edit_date"],
                "verbose_name": "تاریخجه ادیت تماس",
                "verbose_name_plural": "تاریخجه ادیت تماس ها",
            },
        ),
        migrations.AlterField(
            model_name="call",
            name="call_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاریخ تماس"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="call_result",
            field=models.CharField(
                blank=True,
                choices=[
                    ("interested", "Interested"),
                    ("no_time", "No time"),
                    ("not_interested", "Not interested"),
                ],
                max_length=50,
                null=True,
                verbose_name="جزییات تماس",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="caller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تماس گیرنده",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="contacts.contact",
                verbose_name="مخاطب",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ایجاد شده در"),
        ),
        migrations.AlterField(
            model_name="call",
            name="detailed_report",
            field=models.TextField(blank=True, verbose_name="جزییات گزارش"),
        ),
        migrations.AlterField(
            model_name="call",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="مدت تماس(به ثانیه)"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="edit_reason",
            field=models.TextField(blank=True, verbose_name="دلیل تغییر"),
        ),
        migrations.AlterField(
            model_name="call",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تغییر داده شده در"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_calls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تغییر کرده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="feedback",
            field=models.TextField(blank=True, verbose_name="بازخورد"),
        ),
        migrations.AlterField(
            model_name="call",
            name="follow_up_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ پیگیری"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="follow_up_required",
            field=models.BooleanField(
                default=False, verbose_name="نیاز به پیگیری دارد"
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="is_editable",
            field=models.BooleanField(default=True, verbose_name="قابل تغییر"),
        ),
        migrations.AlterField(
            model_name="call",
            name="notes",
            field=models.TextField(blank=True, verbose_name="یادداشت"),
        ),
        migrations.AlterField(
            model_name="call",
            name="original_data",
            field=models.JSONField(blank=True, verbose_name="داده اورجینال"),
        ),
        migrations.AlterField(
            model_name="call",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="projects.project",
                verbose_name="پروژه",
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="status",
            field=models.CharField(
                choices=[
                    ("wrong_number", "Wrong number"),
                    ("answered", "Answered"),
                    ("no_answer", "No answer"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="callanswer",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="calls.call",
                verbose_name="تماس",
            ),
        ),
        migrations.AlterField(
            model_name="callanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.question",
                verbose_name="سوال",
            ),
        ),
        migrations.AlterField(
            model_name="callanswer",
            name="selected_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.answerchoice",
                verbose_name="گزینه انتخاب شده",
            ),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edit_history",
                to="calls.call",
                verbose_name="تماس",
            ),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="edit_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="تاریخ تغییر"
            ),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="edit_reason",
            field=models.TextField(blank=True, verbose_name="دلیل تغییر"),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="edited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_edits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تفییر داده شده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="field_name",
            field=models.CharField(max_length=50, verbose_name="نام فیلد"),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="new_value",
            field=models.TextField(blank=True, verbose_name="ارزش جدید"),
        ),
        migrations.AlterField(
            model_name="calledithistory",
            name="old_value",
            field=models.TextField(blank=True, verbose_name="ارزش گذشته"),
        ),
    ]
