# Generated by Django 5.2.5 on 2025-09-13 06:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='شماره موبایل')),
                ('can_create_projects', models.BooleanField(default=False, verbose_name='می\u200cتواند پروژه بسازد')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CachedStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(max_length=50, verbose_name='نوع آمار')),
                ('stat_key', models.CharField(max_length=100, verbose_name='کلید آمار')),
                ('stat_value', models.TextField(verbose_name='مقدار آمار')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='محاسبه شده در')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضا در')),
            ],
            options={
                'verbose_name': 'آمار کش شده',
                'verbose_name_plural': 'آمارهای کش شده',
                'ordering': ['-calculated_at'],
                'unique_together': {('stat_type', 'stat_key')},
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تماس')),
                ('call_result', models.CharField(choices=[('answered', 'پاسخ داد'), ('no_answer', 'پاسخ نداد'), ('busy', 'مشغول'), ('unreachable', 'در دسترس نیست'), ('wrong_number', 'شماره اشتباه'), ('not_interested', 'علاقه\u200cمند نیست'), ('callback_requested', 'درخواست تماس مجدد')], max_length=50, verbose_name='نتیجه تماس')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('follow_up', 'نیاز به پیگیری'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('feedback', models.TextField(blank=True, verbose_name='بازخورد')),
                ('detailed_report', models.TextField(blank=True, verbose_name='گزارش تفصیلی')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت تماس (ثانیه)')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='نیاز به پیگیری')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پیگیری')),
                ('is_editable', models.BooleanField(default=True, verbose_name='قابل ویرایش')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ویرایش')),
                ('edit_reason', models.TextField(blank=True, verbose_name='دلیل ویرایش')),
                ('original_data', models.TextField(blank=True, verbose_name='داده\u200cهای اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='تماس\u200cگیرنده')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_calls', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش شده توسط')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس\u200cها',
                'ordering': ['-call_date'],
            },
        ),
        migrations.CreateModel(
            name='CallEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ویرایش')),
                ('field_name', models.CharField(max_length=50, verbose_name='نام فیلد')),
                ('old_value', models.TextField(blank=True, verbose_name='مقدار قبلی')),
                ('new_value', models.TextField(blank=True, verbose_name='مقدار جدید')),
                ('edit_reason', models.TextField(blank=True, verbose_name='دلیل ویرایش')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='call_center.call', verbose_name='تماس')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_edits', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش شده توسط')),
            ],
            options={
                'verbose_name': 'تاریخچه ویرایش تماس',
                'verbose_name_plural': 'تاریخچه ویرایش تماس\u200cها',
                'ordering': ['-edit_date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('call_status', models.CharField(choices=[('pending', 'در انتظار تماس'), ('contacted', 'تماس گرفته شده'), ('follow_up', 'نیاز به پیگیری'), ('completed', 'تکمیل شده'), ('not_interested', 'علاقه\u200cمند نیست')], default='pending', max_length=20, verbose_name='وضعیت تماس')),
                ('last_call_date', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تماس')),
                ('custom_fields', models.TextField(blank=True, verbose_name='فیلدهای سفارشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('assigned_caller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='تماس\u200cگیرنده تخصیص داده شده')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contact', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مخاطب')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبین',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='call',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='call_center.contact', verbose_name='مخاطب'),
        ),
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='اقدام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='call_center.contact', verbose_name='مخاطب')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام شده توسط')),
            ],
            options={
                'verbose_name': 'لاگ مخاطب',
                'verbose_name_plural': 'لاگ\u200cهای مخاطب',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('completed', 'تکمیل شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
                'permissions': [('manage_project', 'Can manage project')],
            },
        ),
        migrations.CreateModel(
            name='ExportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('excel', 'اکسل'), ('csv', 'CSV'), ('pdf', 'PDF')], max_length=50, verbose_name='نوع صادرات')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسیر فایل')),
                ('filters', models.TextField(blank=True, verbose_name='فیلترها')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رکوردها')),
                ('export_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صادرات')),
                ('exported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_reports', to=settings.AUTH_USER_MODEL, verbose_name='صادر شده توسط')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_reports', to='call_center.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'گزارش صادر شده',
                'verbose_name_plural': 'گزارش\u200cهای صادر شده',
                'ordering': ['-export_date'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='call_center.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='call',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='call_center.project', verbose_name='پروژه'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'ادمین'), ('caller', 'تماس\u200cگیرنده'), ('contact', 'مخاطب')], max_length=20, verbose_name='نقش در پروژه')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_center.project', verbose_name='پروژه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضویت در پروژه',
                'verbose_name_plural': 'عضویت\u200cها در پروژه\u200cها',
                'ordering': ['-assigned_at'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='call_center.ProjectMembership', to=settings.AUTH_USER_MODEL, verbose_name='اعضای پروژه'),
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=100, verbose_name='نام جستجو')),
                ('search_criteria', models.TextField(verbose_name='معیارهای جستجو')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جستجوی ذخیره شده',
                'verbose_name_plural': 'جستجوهای ذخیره شده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسیر فایل')),
                ('file_type', models.CharField(choices=[('contacts', 'مخاطبین'), ('callers', 'تماس\u200cگیرندگان')], max_length=20, verbose_name='نوع فایل')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رکوردها')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='call_center.project', verbose_name='پروژه')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='آپلود شده توسط')),
            ],
            options={
                'verbose_name': 'فایل آپلود شده',
                'verbose_name_plural': 'فایل\u200cهای آپلود شده',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('project', 'phone')},
        ),
        migrations.CreateModel(
            name='CallStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_calls', models.PositiveIntegerField(default=0, verbose_name='تعداد کل تماس\u200cها')),
                ('successful_calls', models.PositiveIntegerField(default=0, verbose_name='تماس\u200cهای موفق')),
                ('last_call_date', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تماس')),
                ('last_call_result', models.CharField(blank=True, max_length=50, verbose_name='نتیجه آخرین تماس')),
                ('response_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نرخ پاسخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_statistics', to='call_center.contact', verbose_name='مخاطب')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_statistics', to='call_center.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'آمار تماس',
                'verbose_name_plural': 'آمار تماس\u200cها',
                'ordering': ['-updated_at'],
                'unique_together': {('contact', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL, verbose_name='تماس\u200cگیرنده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_callers', to='call_center.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تخصیص تماس\u200cگیرنده',
                'verbose_name_plural': 'تخصیص تماس\u200cگیرندگان',
                'ordering': ['assigned_at'],
                'unique_together': {('project', 'caller')},
            },
        ),
    ]
