# Generated by Django 5.2.5 on 2025-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='detailed_report',
            field=models.TextField(blank=True, verbose_name='گزارش تفصیلی'),
        ),
        migrations.AddField(
            model_name='call',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='بازخورد'),
        ),
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('follow_up', 'نیاز به پیگیری'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='contact',
            name='call_status',
            field=models.CharField(choices=[('pending', 'در انتظار تماس'), ('contacted', 'تماس گرفته شده'), ('follow_up', 'نیاز به پیگیری'), ('completed', 'تکمیل شده'), ('not_interested', 'علاقه\u200cمند نیست')], default='pending', max_length=20, verbose_name='وضعیت تماس'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_call_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تماس'),
        ),
    ]
