# Generated by Django 5.2.5 on 2025-09-04 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='اقدام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='call_center.contact', verbose_name='مخاطب')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انجام شده توسط')),
            ],
            options={
                'verbose_name': 'لاگ مخاطب',
                'verbose_name_plural': 'لاگ\u200cهای مخاطب',
                'ordering': ['-timestamp'],
            },
        ),
    ]
