# Generated by Django 5.2.5 on 2025-09-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0002_contactlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('caller', 'تماس\u200cگیرنده'), ('regular', 'کاربر معمولی'), ('admin', 'ادمین')], default='regular', max_length=20, verbose_name='نقش کاربر'),
        ),
    ]
