# Generated by Django 5.2.5 on 2025-09-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0003_contact_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
