# Generated by Django 5.2.5 on 2025-09-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0005_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
