# Generated by Django 5.2.5 on 2025-09-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0006_project_show'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together=set(),
        ),
    ]
