# Generated by Django 5.2.5 on 2025-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0008_alter_call_call_result_alter_call_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='custom_fields',
            field=models.TextField(blank=True, null=True, verbose_name='فیلدهای سفارشی'),
        ),
    ]
