# Generated by Django 5.2.5 on 2025-09-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0009_alter_contact_custom_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
