# Generated by Django 5.2.5 on 2025-09-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0010_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('project', 'phone')},
        ),
    ]
