# Generated by Django 5.2.5 on 2025-09-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0011_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(verbose_name='تاریخ ایجاد'),
        ),
    ]
