# Generated by Django 5.2.5 on 2025-10-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0013_alter_call_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('none', 'ترجیح میدهم که نگویم')], default='none', max_length=20),
        ),
    ]
