# Generated by Django 5.2.5 on 2025-10-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0014_contact_birth_date_contact_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='متن سوال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='call_center.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='متن گزینه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='call_center.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه پاسخ',
                'verbose_name_plural': 'گزینه\u200cهای پاسخ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CallAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_answer', models.CharField(blank=True, max_length=200, verbose_name='پاسخ سفارشی (اختیاری)')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='call_center.call', verbose_name='تماس')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='call_center.answerchoice', verbose_name='گزینه انتخاب\u200cشده')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_center.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ تماس',
                'verbose_name_plural': 'پاسخ\u200cهای تماس',
                'unique_together': {('call', 'question')},
            },
        ),
    ]
