# Generated by Django 5.2.5 on 2025-10-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0015_question_answerchoice_callanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'verbose_name': 'گزینه پاسخ', 'verbose_name_plural': 'گزینه\u200cهای پاسخ'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.RemoveField(
            model_name='answerchoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
    ]
