# Generated by Django 5.2.5 on 2025-10-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0016_alter_answerchoice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
