# Generated by Django 5.2.5 on 2025-10-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0017_remove_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callanswer',
            name='custom_answer',
        ),
    ]
