# Generated by Django 5.2.5 on 2025-10-11 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0018_remove_callanswer_custom_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='متن')),
                ('done', models.BooleanField(default=False, verbose_name='انجام شده ')),
                ('created_at', models.DateField(auto_now=True, verbose_name='ساخته شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='سازنده')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها ',
                'ordering': ['-created_at'],
            },
        ),
    ]
