# Generated by Django 5.2.5 on 2025-11-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[("excel", "اکسل"), ("csv", "CSV"), ("pdf", "PDF")],
                        max_length=50,
                        verbose_name="نوع صادرات",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="نام فایل"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="مسیر فایل"),
                ),
                ("filters", models.TextField(blank=True, verbose_name="فیلترها")),
                (
                    "records_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد رکوردها"
                    ),
                ),
                (
                    "export_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ صادرات"
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش صادر شده",
                "verbose_name_plural": "گزارش\u200cهای صادر شده",
                "ordering": ["-export_date"],
            },
        ),
        migrations.CreateModel(
            name="CachedStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stat_type", models.CharField(max_length=50, verbose_name="نوع آمار")),
                (
                    "stat_key",
                    models.CharField(max_length=100, verbose_name="کلید آمار"),
                ),
                ("stat_value", models.TextField(verbose_name="مقدار آمار")),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="محاسبه شده در"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="انقضا در"
                    ),
                ),
            ],
            options={
                "verbose_name": "آمار کش شده",
                "verbose_name_plural": "آمارهای کش شده",
                "ordering": ["-calculated_at"],
                "unique_together": {("stat_type", "stat_key")},
            },
        ),
        migrations.CreateModel(
            name="CallStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_calls",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد کل تماس\u200cها"
                    ),
                ),
                (
                    "successful_calls",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تماس\u200cهای موفق"
                    ),
                ),
                (
                    "last_call_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تماس"
                    ),
                ),
                (
                    "last_call_result",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نتیجه آخرین تماس"
                    ),
                ),
                (
                    "response_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="نرخ پاسخ",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروزرسانی"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_statistics",
                        to="contacts.contact",
                        verbose_name="مخاطب",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_statistics",
                        to="projects.project",
                        verbose_name="پروژه",
                    ),
                ),
            ],
            options={
                "verbose_name": "آمار تماس",
                "verbose_name_plural": "آمار تماس\u200cها",
                "ordering": ["-updated_at"],
            },
        ),
    ]
