# Generated by Django 5.2.5 on 2025-11-04 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportreport',
            name='exported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_reports', to=settings.AUTH_USER_MODEL, verbose_name='صادر شده توسط'),
        ),
        migrations.AddField(
            model_name='exportreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_reports', to='projects.project', verbose_name='پروژه'),
        ),
        migrations.AlterUniqueTogether(
            name='callstatistics',
            unique_together={('contact', 'project')},
        ),
    ]
