# Generated by Django 5.2.5 on 2025-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='متن گزینه')),
            ],
            options={
                'verbose_name': 'گزینه پاسخ',
                'verbose_name_plural': 'گزینه\u200cهای پاسخ',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='متن سوال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=100, verbose_name='نام جستجو')),
                ('search_criteria', models.TextField(verbose_name='معیارهای جستجو')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'جستجوی ذخیره شده',
                'verbose_name_plural': 'جستجوهای ذخیره شده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسیر فایل')),
                ('file_type', models.CharField(choices=[('contacts', 'مخاطبین'), ('callers', 'تماس\u200cگیرندگان')], max_length=20, verbose_name='نوع فایل')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رکوردها')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'فایل آپلود شده',
                'verbose_name_plural': 'فایل\u200cهای آپلود شده',
                'ordering': ['-upload_date'],
            },
        ),
    ]
