# Generated by Django 5.2.5 on 2025-11-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_alter_call_options_alter_callanswer_options_and_more"),
        ("files", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="project",
        ),
        migrations.DeleteModel(
            name="AnswerChoice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
