# Generated by Django 5.2.5 on 2025-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='متن')),
                ('done', models.BooleanField(default=False, verbose_name='انجام شده ')),
                ('created_at', models.DateField(auto_now=True, verbose_name='ساخته شده')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها ',
                'ordering': ['-created_at'],
            },
        ),
    ]
