# Generated by Django 5.2.5 on 2025-12-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ساخته شده"),
        ),
    ]
